"""empty message

Revision ID: 6b61fc020e14
Revises: 984f0688a056
Create Date: 2022-05-20 15:04:17.670394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b61fc020e14'
down_revision = '984f0688a056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'user_id')
    # ### end Alembic commands ###
