name : Newman Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: matt-ball/newman-action@master
      with:
        collection: https://www.getpostman.com/collections/5153dbb5888f726d7c46
